### ISSUE TITLE
Dev dependencies are showing up as base dependencies

### ISSUE THREAD

**Issue by jace** [TGoddessana/flask-moreshell#127]
Adding `flask-moreshell` as a dependency to my project has caused `pip-compile` to also add the following:

* `furo`
* `nox`
* `nox-poetry`

These have recursively added more dependencies:

* `alabaster` (via `sphinx`)
* `argcomplete` (via `nox`)
* `beautifulsoup4` (via `furo`)
* `colorlog` (via `nox`)
* `distlib` (via `virtualenv`)
* `docutils` (via `sphinx`)
* `filelock` (via `virtualenv`)
* `imagesize` (via `sphinx`)
* `platformdirs` (via `virtualenv`)
* `pygments` (via `furo` and `sphinx`)
* `snowballstemmer` (via `sphinx`)
* `soupsieve` (via `beautifulsoup4`)
* `sphinx` (via `furo`)
* `sphinx-basic-ng` (via `furo`)
* `sphinxcontrib-applehelp` (via `sphinx`)
* `sphinxcontrib-devhelp` (via `sphinx`)
* `sphinxcontrib-htmlhelp` (via `sphinx`)
* `sphinxcontrib-jsmath` (via `sphinx`)
* `sphinxcontrib-qthelp` (via `sphinx`)
* `sphinxcontrib-serializinghtml` (via `sphinx`)
* `tomlkit` (via `nox-poetry`)
* `virtualenv` (via `nox`)

None of these dependencies are needed for `flask shell`, so this appears to be an accident of including `furo`, `nox` and `nox-poetry` under `[tool.poetry.dependencies]` in `pyproject.toml`. `furo` also appears in `[tool.poetry.group.development.dependencies]` with a different version spec.

**Comment by TGoddessana** [comment]
hello!
Thank you for bringing this to our attention.

[This PR](https://github.com/TGoddessana/flask-moreshell/pull/128/files#diff-50c86b7ed8ac2cf95bd48334961bf0530cdc77b5a56f852c5c61b89d735fd711) should have fixed the issue. 

We've also released a [new version 0.1.5 on PyPI](https://pypi.org/project/flask-moreshell/).
Thanks a lot!
